name: Bug Report
description: Report a bug or an issue in the game.
labels: ["type: minor bug", "status: pending triage"]
title: "Bug Report: "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have properly named my issue
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported

  - type: dropdown
    attributes:
      label: Installed Mods
      description: Did you have any other mods installed when encountering this bug?
      options:
        - I did not have any mods installed other than Spooky Mix
        - I did have other mods installed
    validations:
      required: true

  - type: textarea
    attributes:
      label: 
      description: If so, please list all of the mods you had installed here.
      placeholder: List your installed mods other than Spooky Mix
        
  - type: dropdown
    attributes:
      label: Download Source
      description: Where did you download the mod from?
      options:
        - Gamebanana
        - Game Jolt
        - Google Drive
        - Github
    validations:
      required: true

  - type: input
    attributes:
      label: Friday Night Funkin' Version
      description: Which version of FNF are you playing on? The game version is in the bottom left corner of the main menu. 
      placeholder: ex. 0.6.0
    validations:
      required: true
  
  - type: input
    attributes:
      label: Spooky Mix Version
      description: Which version of Spooky Mix are you playing on? The mod version is in the bottom right corner of the main menu. 
      placeholder: ex. 2.0.0
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: "## Describe your bug."

  - type: markdown
    attributes:
      value: "### Please do not report issues from other engine ports of Spooky Mix."

  - type: textarea
    attributes:
      label: Description (include any images, videos, errors, or crash logs)
      description: Provide as much detail as you can. The better others understand your issue, the more they can help you!  
      placeholder: Describe your issue here...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps can other people take to reliably encounter this issue?
      placeholder: 1. Open the game...
