name: Crash Report
description: Report a crash that occurred while playing the game.
labels: ["type: major bug", "status: pending triage"]
title: "Crash Report: "
body:
  - type: checkboxes
    attributes:
      label: Issue Checklist
      description: Be sure to complete these steps to increase the chances of your issue being addressed!
      options:
        - label: I have properly named my issue
        - label: I have checked the Issues/Discussions pages to see if my issue has already been reported

  - type: dropdown
    attributes:
      label: Download Source
      description: Where did you download the mod from?
      options:
        - Gamebanana
        - Game Jolt
        - Google Drive
        - Github
    validations:
      required: true

  - type: input
    attributes:
      label: Friday Night Funkin' Version
      description: Which version of FNF are you playing on? The game version is in the bottom left corner of the main menu. 
      placeholder: ex. 0.6.0
    validations:
      required: true
  
  - type: input
    attributes:
      label: Spooky Mix Version
      description: Which version of Spooky Mix are you playing on? The mod version is in the bottom right corner of the main menu. 
      placeholder: ex. 2.0.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Installed Mods
      description: Did you have any other mods installed when encountering this crash?
      options:
        - I did not have any mods installed other than Spooky Mix
        - I did have other mods installed
    validations:
      required: true

  - type: textarea
    attributes:
      label: If so, please list all of the mods you had installed here.
      placeholder: List your installed mods other than Spooky Mix

  - type: markdown
    attributes:
      value: "## Describe the crash."

  - type: markdown
    attributes:
      value: "### Please do not report issues from other engine ports of Spooky Mix."

  - type: textarea
    attributes:
      label: Description
      description: Include screenshots or videos of the crash happening. Provide as much detail as you can. 
      placeholder: Describe the crash here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What steps can other people take to reliably trigger this crash?
      placeholder: 1. Open the game...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Crash logs
      description: These can be found in the logs folder where Funkin.exe is.
      placeholder: Upload your logs here...
    validations:
      required: true
